apiVersion: v1
kind: ConfigMap
metadata:
  name: immichframe-settings
  namespace: immich
data:
  Settings.yaml: |
    General:
      RenewImagesDuration: 30
      Interval: 45
      TransitionDuration: 2
      ShowClock: false
      ClockFormat: 'hh:mm'
      ShowProgressBar: false
      ShowPhotoDate: false
      ShowImageDesc: false
      ShowPeopleDesc: true
      ShowAlbumName: false
      ShowImageLocation: false
      ImageZoom: false
      Layout: splitview
    Accounts:
      - ImmichServerUrl: http://immich-server.immich.svc.cluster.local:2283
        ApiKey: rRnNf0d89PKCgR6zePuaT5xGm7S56ymVYHseRtfsXE4
        ShowMemories: false
        Albums:
          - 6273df24-6194-46ea-95e0-b6e70e88f554
