apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name:  nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  mountPermissions: '0755'
  server: 10.10.10.10                # your Synology IP
  share: /volume1/k8s-csi            # your exported NFS path
mountOptions:
  - nfsvers=4.1
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-notes
  labels:
    app: notes
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes: [ ReadWriteMany ]
  persistentVolumeReclaimPolicy: Retain
  # Optional after you confirm manually:
  mountOptions: [ vers=4.1 ]
  nfs:
    server: 10.10.10.10
    path: /volume1/k8s-persistent-volume/notes

