apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name:  nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  mountPermissions: '0755'
  server: 10.10.10.10                # your Synology IP
  share: /volume1/k8s-csi            # your exported NFS path
mountOptions:
  - nfsvers=4.1
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-csi-retain
provisioner: nfs.csi.k8s.io
spec:
  storageClassName: nfs-csi-retain-class
  capacity:
    storage: 10Gi # Adjust as needed
  accessModes:
    - ReadWriteMany # Or ReadWriteOnce, ReadOnlyMany depending on your needs
  persistentVolumeReclaimPolicy: Retain # Or Delete, Recycle
  nfs:
    path: /volume1/k8s-persistent-volume # The exported path on your NFS server
    server:  10.10.10.10          # IP or hostname of your NFS server
