apiVersion: apps/v1
kind: Deployment
metadata:
  name: tron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tron
  template:
    metadata:
      labels:
        app: tron
    spec:
      volumes:
        - name: ssh
          secret:
            secretName: git-ssh-key
            defaultMode: 0400
        - name: users
          persistentVolumeClaim:
            claimName: users
        - name: data
          persistentVolumeClaim:
            claimName: data
      containers:
        - name: app
          volumeMounts:
            - name: users
              mountPath: /app/users
            - name: data
              mountPath: /app/data
            - name: tronbyt_server
              mountPath: /app/tronbyt_server
          image: ghcr.io/tronbyt/server:latest
          ports:
            - name: http
              containerPort: 8000
          readinessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: tron
spec:
  selector:
    app: tron
  ports:
    - name: http
      port: 80
      targetPort: http                 # matches the container's named port