apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: immich
spec:
  project: default
  source:
    repoURL: https://immich-app.github.io/immich-charts
    chart: immich
    targetRevision: "*"
    helm:
      valueFiles:
        - immich/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true