apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://immich-app.github.io/immich-charts
    chart: immich
    targetRevision: "*"
    helm:
      releaseName: immich
      values: |
        controllers:
          main:
            containers:
              main:
                env:
                  DB_HOSTNAME: immich-postgres
                  DB_USERNAME: immich
                  DB_PASSWORD: immich
                  DB_DATABASE_NAME: immich
                  REDIS_HOSTNAME: immich-valkey
        immich:
          persistence:
            library:
              existingClaim: immich-library
        valkey:
          enabled: true
        machine-learning:
          enabled: false
        server:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true