apiVersion: apps/v1
kind: Deployment
metadata:
  name: focus-api
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: focus-api
  template:
    metadata:
      labels:
        app: focus-api
    spec:
      volumes:
        - name: repo
          persistentVolumeClaim:
            claimName: pvc-notes      # <-- PVC name
      containers:
        - name: app
          volumeMounts:
            - name: ssh
              mountPath: /home/app/.ssh
              readOnly: true
            - name: repo
              mountPath: /app/notes
          image:
            ghcr.io/kadinvanvalin/focus-api:sha-c01340cf8f72cf8b2712d2a88949c7573ee718b4470ec685de43f5b57645042f
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet: { path: /healthz, port: http }
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /healthz, port: http }
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: focus-api
spec:
  selector:
    app: focus-api
  ports:
    - name: http
      port: 80
      targetPort: http                 # matches the container's named port