apiVersion: apps/v1
kind: Deployment
metadata:
  name: focus-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: focus-api
  template:
    metadata:
      labels:
        app: focus-api
    spec:
      containers:
        - name: app
          image: ghcr.io/kadinvanvalin/focus-api:sha-3e7624c1cd6a131aa7cc49455f53782b0caeea7c@sha256:2a1b0f3ae7937ed184faf2a14bf97d349f6e6654ab841d5a8ce38f236df6c21d
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: http               # refer to the named port
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: focus-api
spec:
  selector:
    app: focus-api
  ports:
    - name: http
      port: 80
      targetPort: http                 # matches the container's named port