apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary
spec:
  replicas: 1
  selector: { matchLabels: { app: canary } }
  template:
    metadata: { labels: { app: canary } }
    spec:
      containers:
        - name: app
          image: traefik/whoami
          ports: [{ containerPort: 8000 }]
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 2
        periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: canary
spec:
  selector: { app: canary }
  ports:
    - name: http
      port: 80
      targetPort: 8000